In [1]:
import numpy as np



In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6],
    [7, 8, 9]
])
print (matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#To get the value at the given index 
number_six = matrix[1][2]
print(number_six)

6
