#                                                              MATHS FOR DATA SCIENCE

In [43]:
# standard deviation is how dispersed data is in a given set
import numpy as np
from  scipy import stats


# STATISTICS
- mean/median/mode - descriptive statistics
- population  - inferencial statistics
- Hypotheses - A claim yet to be proven(NULL/ALTERNATIVE)
- Standard deviation

In [44]:
data = [2,3,4,5,6,7,8,9,2,1]
std_dev = np.std(data)
print("Standard Deviation : " +  str(std_dev) )

Mean = np.mean(data)
print("Mean : " + str(Mean))

Median = np.median(data)
print("Median : " + str(Median))

Mode = stats.mode(data)
print("Mode : " + str(Mode))

Standard Deviation : 2.6095976701399777
Mean : 4.7
Median : 4.5
Mode : ModeResult(mode=2, count=2)


# LINEAR ALGEBRA
- Scalar
- Vectors
- Matrices


# VECTORS
- properties/laws
- Addition(Commutative*/Associative*/Additive Identity*/Additive Inverse*/Distributive vectors*/Distributive scalar*/Associative scalar)
- Subtraction(Commutative*/Associative*/Distributive scalar*/)

In [45]:
# we can import an algorithim in this way from        (sklearn.linear_model import LinearRegression)
# Scalar is a quantity that has magnitude
# Vectors is a quantity that has both magnitude and direction
# Since Machines understand numbers data is stored in Vectors, Matrices and Tensors


# how to create a vector in python 
Q = np.array([3,4,5,6,7,8,9,4,8])
P = np.array([2,4,6,8])
W = np.array([8,6,4,2])
print("This is a vector Q : "+ str(Q))
dot_product = P@W
print("The dot product of vector P and W is : " + str(dot_product))
# we can find the dot product of vectors using this (p@u/ .dot())

This is a vector Q : [3 4 5 6 7 8 9 4 8]
The dot product of vector P and W is : 80


# MATRICES
TYPES OF MATRICES
- Square matrix
- Tall matrix
- Wide matrix
- Row vector
- Scalar matrix
- Zero matrix 
- Identity matrix
- Sparse matrix
- Diagonal matrix
- Triangular matrix

In [46]:
print("Sample vector "+ str(Q))
np.shape(Q)
MatrixA = np.array([[1,2,3], [3,4,5],[6,7,8]])
MatrixB = np.array([[3,2,3], [3,4,9],[6,2,8]])
MatrixC = np.array([[1,4,3], [3,8,5],[5,7,8]])

print("Sample matrix "+ str(Matrix) )
np.shape(Matrix)

Sample vector [3 4 5 6 7 8 9 4 8]
Sample matrix [[1 2 3]
 [3 4 5]
 [6 7 8]]


(3, 3)

# MATRIX OPERATIONS
- Addition
- Subtraction
- Transpose

In [49]:
#ADDITION OF MATRICES
Add = MatrixA + MatrixB
print(Add)

#SUBTRACTION
Sub = MatrixA - MatrixB
print(Sub)

#TRANSPOSE OF A MATRIX
Trans = np.transpose(MatrixA)
print(Trans)


[[ 4  4  6]
 [ 6  8 14]
 [12  9 16]]
[[-2  0  0]
 [ 0  0 -4]
 [ 0  5  0]]
[[1 3 6]
 [2 4 7]
 [3 5 8]]


# APPLICATIONS OF MATRICES
- Data representation and storage
Image processing
Graphs and networks

- Linear algebra-:

Linear Regression
Principal Components Analysis(PCA)-Dimensionality reduction techniques that uses matrix operations to identify the most important underlying patterns
Eigen Values and Eigen Vectors-Reveal important information about the data 

- Machine learning-:
Univariate /Bivariate/ Multivariate AnLysis
Deep Learning- Convolutional Neural Networks(CNNs)-backbone of deep learning operations they heavily rely on matrix operations for Feature Extraction and Image recognition